default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: timecard_kun_development

test:
  <<: *default
  database: timecard_kun_test

#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
